DROP TABLE ROLE;

CREATE TABLE ROLE (
ID INT PRIMARY KEY AUTO_INCREMENT,
ROLE_CODE VARCHAR(10) NOT NULL,
ROLE_NAME VARCHAR(100) NOT NULL,
LEVEL INT NOT NULL,
ACTIVE TINYINT DEFAULT 1,
CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT ROLE_CODE_UQ UNIQUE ( ROLE_CODE),
CONSTRAINT ROLE_NAME_UQ UNIQUE ( ROLE_NAME)
);

INSERT INTO ROLE ( ROLE_CODE, ROLE_NAME, LEVEL)
VALUES 
('SR011', 'System Admin', 11),
('SR010', 'Managing Director', 10),
('SR009', 'Director', 9),
('SR008', 'HR Manager',8),
('SR007', 'HR', 7),
('SR006', 'Admin Officer', 6),
('SR005', 'Admin', 5),
('SR004', 'Group Manager', 4),
('SR003', 'Reporting Manager', 3),
('SR002', 'Employee', 2),
('SR001', 'Trainee', 1);


SELECT * FROM ROLE;